apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: nginx-replicaset
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nginx-app
      
  template: 
    metadata:
      labels:
        environment: development
        app: nginx-app
    spec:
      containers:
        - name: nginx-rs-container 
          image:  nginx:latest 
          ports:
            - containerPort: 80