apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongodb
spec:
  selector:
    matchLabels:
      app: mongodb
  replicas: 1
  template:
    metadata:
      labels:
        app: mongodb
    spec:
      containers:
        - name: mongodb
          image: mongo
          volumeMounts:
            - mountPath: /data/db
              name: mongo-persistent-store
      volumes:
        - name: mongo-persistent-store
#          hostPath:
#            path: /opt/kube/mongo
#            type: DirectoryOrCreate
          persistentVolumeClaim:
            claimName: mongo-pvc

---
apiVersion: v1
kind: Service
metadata:
  name: fleetman-mongodb
spec:
    selector:
      app: mongodb
    ports:
      - name: mongodbport
        port: 27017
    type: ClusterIP
