# Localstorage - mongo-pvc
# what do we want ?
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mongo-pvc
spec:
  storageClassName: mystorageclass
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi

---
# how do we want it to be implemented

apiVersion: v1
kind: PersistentVolume
metadata:
  name: local-storage
spec:
  storageClassName: mystorageclass # for linking purpose with PVC [PersistentVolumeClaim]
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 2Gi
  hostPath:
    path: /opt/kube/claim
    type: DirectoryOrCreate
